import { useCallback, useEffect, useState } from 'react';
import { ArrowRight, Eye, MapPin, Search, UsersRound } from 'lucide-react';
import { Button, EmptyState, ErrorState, Input, LoadingState } from '../../components/ui/index.js';
import { publicApi } from '../../api/public.api.js';
import { toApiError } from '../../api/client.js';
import { money } from '../../lib/format.js';
import { usePageTitle } from '../../hooks/usePageTitle.js';

const CommunityPage = () => {
  usePageTitle('Community trips'); const [search, setSearch] = useState(''); const [sort, setSort] = useState('recent'); const [state, setState] = useState({ loading: true, error: null, items: [] });
  const load = useCallback(async () => { setState((old) => ({ ...old, loading: true, error: null })); try { const data = await publicApi.listTrips({ search, sort, limit: 24 }); setState({ loading: false, error: null, items: data.items }); } catch (error) { setState((old) => ({ ...old, loading: false, error: toApiError(error) })); } }, [search, sort]);
  useEffect(() => { const timer = window.setTimeout(load, 250); return () => window.clearTimeout(timer); }, [load]);
  return <section className="mx-auto max-w-6xl px-4 pb-16"><div className="rounded-4xl bg-moss-800 px-6 py-8 text-canvas sm:px-9"><UsersRound className="size-6 text-moss-300"/><h1 className="mt-4 max-w-xl font-display text-4xl font-semibold">Borrow a little inspiration.</h1><p className="mt-3 max-w-xl text-sm leading-relaxed text-canvas/70">Explore public trips shared by travellers, then copy one into your own account and make it yours.</p></div><div className="mt-7 flex flex-col gap-3 rounded-3xl border border-line bg-surface p-3 sm:flex-row"><Input wrapperClassName="mb-0 flex-1" aria-label="Search community trips" icon={Search} placeholder="Search trips" value={search} onChange={(event) => setSearch(event.target.value)}/><select className="h-12 rounded-2xl border border-line bg-canvas px-4 text-sm" value={sort} onChange={(event) => setSort(event.target.value)} aria-label="Sort community trips"><option value="recent">Most recent</option><option value="popular">Most viewed</option><option value="name">Name A-Z</option></select></div>{state.loading ? <div className="mt-7"><LoadingState label="Opening the community map"/></div> : state.error ? <div className="mt-7"><ErrorState error={state.error} retry={load}/></div> : state.items.length === 0 ? <div className="mt-7"><EmptyState title="No public trips yet" description="Share the first itinerary and set the tone."/></div> : <div className="mt-7 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{state.items.map((trip) => <article key={trip.publicSlug} className="overflow-hidden rounded-4xl border border-line bg-surface shadow-soft"><div className="h-32 bg-gradient-to-br from-dusk-400 via-clay-400 to-moss-600" style={trip.coverPhotoUrl ? { backgroundImage: `linear-gradient(rgba(23,20,15,.12), rgba(23,20,15,.65)), url(${trip.coverPhotoUrl})`, backgroundSize: 'cover', backgroundPosition: 'center' } : undefined}/><div className="p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-display text-2xl font-semibold">{trip.name}</h2><p className="mt-1 text-sm text-ink-500">by {trip.owner.firstName}</p></div>{trip.owner.avatarUrl && <img className="size-9 rounded-full object-cover" src={trip.owner.avatarUrl} alt=""/>}</div><p className="mt-4 line-clamp-2 min-h-10 text-sm leading-relaxed text-ink-500">{trip.description || 'A shared route worth exploring.'}</p><p className="mt-4 flex items-center gap-1 text-xs text-ink-500"><MapPin className="size-3.5 text-clay-500" />{trip.cities?.join(' · ') || `${trip.stopCount} cities`}</p><div className="mt-4 flex justify-between border-t border-line pt-4 text-xs text-ink-500"><span className="flex items-center gap-1"><Eye className="size-3.5" />{trip.viewCount} views</span><strong className="text-ink-900">{money(trip.estimatedCost, trip.currency)}</strong></div><Button to={`/t/${trip.publicSlug}`} fullWidth className="mt-5" variant="dark">View trip <ArrowRight className="size-4" /></Button></div></article>)}</div>}</section>;
};
export default CommunityPage;
